once upon a time there was a monkey which was very thirsty... a crocodile came across to help the monkey with some water... and the monkey felt so thankful and it kept visiting the crocodile ofter and they both became good friends.... 


